Add solution for lab 5
systems-cs-pub-ro/so pull request #20
Opened 2022-02-06 20:03 UTC by teodutu

2022-02-12 21:06 UTC, sketch873 commented
In the lab05/skel/lin/ some Makefiles do not have PHONY all

Let only one newline between test.o and clean: lab05/skel/lin/9-my_malloc/Makefile
Leading space: lab05/skel/lin/9-my_malloc/Makefile (libmy_malloc.so)
Let only one newline between macros and main: lab05/sol/lin/3-alloc/alloc.c
Let only one newline between block comments: lab05/skel/win/malloc-wrapper/test.c AND lab05 /sol/win/malloc-wrapper/test.c

There are two years in the descriptions: 2006 and 2011. My suggestion is to remove the year from all files.

2022-02-12 21:20 UTC, sketch873 requested changes

2022-02-12 21:20 UTC, sketch873 commented on labs/lab05/sol/lin/4-gdb/fault.c
> +	upper(message);
upper_string(message);

2022-02-12 21:20 UTC, sketch873 commented on labs/lab05/sol/lin/4-gdb/fault.c
> +	upper_string("Upper string is: %s\n", message);
printf("Upper string is: %s\n", message);

2022-02-12 21:20 UTC, sketch873 commented on labs/lab05/sol/lin/7-trim/trim.c
> +
#include "utils.h"

2022-02-17 16:25 UTC, sketch873 approved these changes

2022-02-20 11:01 UTC, lucigrigo approved these changes

2022-02-26 10:39 UTC, merged