Publish solutions for lab 4
systems-cs-pub-ro/so pull request #23
Opened 2022-02-13 11:05 UTC by sketch873

2022-02-13 16:25 UTC, teodutu requested changes
Looks good! Apart from the direct code suggestions I made, there are a few more things to fix:

- Use `Signals`, not `Semnale` in the block comments at the beginning of `lab04/skel/lin/utils/utils.h` and remove the newline after this comment.
- Remove the extra newline in `lab04/skel/lin/2-signals/send_normal.sh`.
- Use `Linux`, not `lin` in the block comments at the beginning of Linux files.
- Align the `*`'s in the block comments at the beginning of each file. They should be
```c
/**
 *
 */
```
not
```c
/**
  *
  */
```

2022-02-13 16:25 UTC, teodutu commented on labs/lab04/skel/win/1-timer/mytimer.c
> + * SO - Lab #4, Signals
```suggestion
 * SO
 * Lab #4, Signals
```

2022-02-13 16:25 UTC, teodutu commented on labs/lab04/sol/win/1-timer/mytimer.c
> + * SO - Lab #4, Signals
```suggestion
 * SO
 * Lab #4, Signals
```

2022-02-13 16:25 UTC, teodutu commented on labs/lab04/sol/win/utils/utils.h
> + * SO, 2017
```suggestion
 * SO
```

2022-02-13 18:58 UTC, teodutu approved these changes, later dismissed

2022-02-16 14:06 UTC, andreia-oca approved these changes, later dismissed
Looks good to me! I just have two nit comments.

2022-02-16 14:06 UTC, andreia-oca commented on labs/lab04/sol/win/1-timer/mytimer.c
> + * Task #1 Solution, Windows
Remove `Solution` from here because it's redundant.

2022-02-16 14:06 UTC, andreia-oca commented on labs/lab04/sol/win/1-timer/mytimer.c
> +	 */
I think this multi-line comment must be formatted like this:
```
/**
 *
 */
```

2022-02-17 19:55 UTC, teodutu approved these changes

2022-02-23 10:00 UTC, andreia-oca approved these changes

2022-02-28 07:44 UTC, merged