Publish solutions for lab 8
systems-cs-pub-ro/so pull request #24
Opened 2022-02-13 11:38 UTC by sketch873

Signed-off-by: Andrei Martin <andrei.cos.martin@gmail.com>

2022-02-13 16:56 UTC, teodutu requested changes
Apart from some coding style issues, everything looks in order.
Apart from what I wrote as inline code suggestions, please replace `lin` with `Linux` in the block comments of all Linux files.

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +    }
```suggestion
		rc = pthread_join(threads[i], NULL);
		DIE(rc != 0, "pthread_join");
	}
```

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +    }
```suggestion
		rc = pthread_create(&threads[i], NULL, thread_func, (void *) I);
		DIE(rc != 0, "pthread_create");
	}
```

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +	}
```suggestion
	if (!once_control->refcount)
		(*f)();
```

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +   */
```suggestion
	* Call the f() function only if this is the last thread that got here.
	*/
```

Do this to `lab08/skel/lin/6-once/once.c` as well.

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +   */
```suggestion
	* Call the f() function only if this is the first thread that got here.
	*/
```

Do this to `lab08/skel/lin/6-once/once.c` as well.

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +	}
```suggestion
	if (!once_control->refcount)
		(*f)();
```

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +    }
```suggestion
	for (int i = 0; i < NUM_CHARS; i++) {
		printf("%c", START_CHAR + arg);

		/* What happens if you comment out the fflush? */

		fflush(stdout);

		/* What happens if you decrease the PERIOD? */

		usleep(PERIOD);
	}
```

Apply this to `lab08/skel/lin/6-once/once.c` as well.

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/6-once/once.c
> +
```suggestion
```

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/3-safety/malloc.c
> +	(*a)++;
```suggestion
static void increase_numbers(int* a, int* b, int* c)
{
	(*a)++;
```

Do the same for `lab08/skel/lin/3-safety/malloc.c`.

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/3-safety/malloc.c
> +						int *function_specific_storage)
```suggestion
			int *global_storage,
			int *function_global_storage,
			int *function_specific_storage)
```

It just looked weird like that.

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/3-safety/critical.c
> +		}
```suggestion
		if (__atomic_test_and_set(&lock, __ATOMIC_SEQ_CST) == false)
			return;
```

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/3-safety/Makefile
> +
```suggestion
```

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/3-safety/critical.c
> +	while(1) {
```suggestion
	while (1) {
```

The same for `lab08/skel/lin/3-safety/critical.c`.

2022-02-13 16:56 UTC, teodutu commented on labs/lab08/sol/lin/2-th_vs_proc/threads.c
> +	/* Create a thread and assign do_task as its starting function */
```suggestion
		/* Create a thread and assign do_task as its starting function */
```

2022-02-13 20:11 UTC, teodutu approved these changes, later dismissed
I left 3 unresolved comments from before. The changes to the `sol/` folder are fine. Please apply them to the `skel` folder as well.

2022-02-16 14:22 UTC, andreia-oca approved these changes, later dismissed
Looks good to me. 
I have just one general comment. The recommended coding style is one declaration per line, no commas for multiple declarations). I added suggestions in the source code where I spotted this problem.

2022-02-16 14:22 UTC, andreia-oca commented on labs/lab08/sol/lin/7-prodcons/prodcons.c
> +	pthread_t producer_th, consumer_th;
```suggestion
	pthread_t producer_th;
	pthread_t consumer_th;
```

2022-02-16 14:22 UTC, andreia-oca commented on labs/lab08/sol/lin/7-prodcons/prodcons.c
> +	int item_consumed, i, rc;
```suggestion
	int item_consumed;
	int i;
	int rc;
```

2022-02-16 14:22 UTC, andreia-oca commented on labs/lab08/sol/lin/2-th_vs_proc/processes.c
> +	int i, rc;
One declaration per line here also.

2022-02-16 14:22 UTC, andreia-oca commented on labs/lab08/sol/lin/2-th_vs_proc/threads.c
> +	int i, rc;
```suggestion
	int i;
	int rc;
```

2022-02-16 14:22 UTC, andreia-oca commented on labs/lab08/sol/lin/7-prodcons/prodcons.c
> +	int item_to_insert, i, rc;
```suggestion
	int item_to_insert;
	int i;
	int rc;
```

2022-02-17 19:58 UTC, teodutu approved these changes

2022-02-23 09:59 UTC, andreia-oca approved these changes

2022-02-28 07:44 UTC, merged