Publish solutions for lab 12
systems-cs-pub-ro/so pull request #25
Opened 2022-02-17 16:31 UTC by sketch873

2022-02-17 20:08 UTC, teodutu requested changes
On top of the inline suggestions I made, I think you should convert `lab12/sol/lin/1-mini/README` to Markdown format.

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +			arg3 = strtok(NULL, delim);/* fs_type (e.g: ext2) */
```suggestion
			arg3 = strtok(NULL, delim); /* fs_type (e.g: ext2) */
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +/* Recursively list all dirs under 'dirname' path
```suggestion
/**
 * Recursively list all dirs under 'dirname' path
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +		/* TODO2: implement list <device_node>
```suggestion
		/**
		 * TODO2: implement list <device_node>
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +		/* TODO3: implement mount source target fs_type
```suggestion
		/**
		 * TODO3: implement mount source target fs_type
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +		/* TODO4: implement symlink oldpath newpath
```suggestion
		/**
		 * TODO4: implement symlink oldpath newpath
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +		/* TODO5: implement mkdir pathname mode
```suggestion
		/**
		 * TODO5: implement mkdir pathname mode
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +		/* TODO6: implement ls dirname
```suggestion
		/**
		 * TODO6: implement ls dirname
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +			/* TODO7: implement chdir <dir>
```suggestion
			/**
			 * TODO7: implement chdir <dir>
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/mini.c
> +			/* TODO7: implement pwdir
```suggestion
			/**
			 * TODO7: implement pwdir
```

2022-02-17 20:08 UTC, teodutu commented on labs/lab12/sol/lin/1-mini/utils.h
> + *
```suggestion
 * SO
 * Linux
```

2022-02-17 22:54 UTC, teodutu approved these changes, later dismissed

2022-02-23 10:14 UTC, andreia-oca submitted a review, later dismissed

2022-02-23 10:14 UTC, andreia-oca commented on labs/lab12/sol/lin/1-mini/README.md
> +* trebuie incluse `<sys/types.h>` şi `<dirent.h>`
# Additional Hints

## Task 1
* `ls -l /dev` will list all node devices. 
* Check the snippet below:

```
# b - block device, 8 - major, 1 - minor
brw-rw---T 1 root disk 8, 1 May 14 19:50 /dev/sda1
```

## Task 3
* Include `<sys/mount.h>`.

## Task 6
* `man opendir`
* Include `<sys/types.h>` and `<dirent.h>`.

2022-02-23 10:14 UTC, andreia-oca commented on labs/lab12/sol/lin/1-mini/README.md
> +* trebuie incluse `<sys/types.h>` şi `<dirent.h>`
I would translate this whole README in English.

2022-02-23 10:36 UTC, andreia-oca approved these changes

2022-02-23 19:13 UTC, teodutu approved these changes

2022-02-28 07:44 UTC, merged