Add solution for lab02
systems-cs-pub-ro/so pull request #26
Opened 2022-02-21 11:03 UTC by lucigrigo

2022-02-21 21:18 UTC, teodutu requested changes
I left some required changes as inline suggestions. The rest of the suggestions apply globally:

- Remove the `.DS_Store` file
- Revert the indentation from 4 spaces to tabs.
- Use the following style for multiline comments:
```
/**
 *
 */
```
- Use the Linux Kernel coding style for multiline `if`s, `for`s etc:
```c
if (cond) {
	/* stuff */
}
```
- In general, run `checkpatch.pl` and fix the coding style. Ignore the lack of an SPDX license and the CRLF line endings in Windows files.
- Why delete `lab02/skel/win/2-crc/tests/tests_out`? They're useful for veryfing if the CRC is calculated correctly.
- Move `lab02/skel/win/2-crc/tests_in` back to ``lab02/skel/win/2-crc/tests/tests_in`. i.e. put them back inside the `tests` directory, together with `tests_out`.
- Add `lab02/sol/win/2-crc/tests_out` and place them in a `tests` folder, together with `tests_in`, just like the tests files for the skeleton.
- Remove `labs/lab02/sol/.gitignore`. It's empty.
- Remove the block empty line after the block comments at the beginning of `sol` files.

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/skel/win/2-crc/crc.c
> +    /* read from file  */
Keep the capital letter for `read` so it's consistent with the rest of the comments.

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/skel/win/2-crc/crc.c
> -}
Why delete this? It is necessary to write the CRC to the file.

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/skel/win/2-crc/crc.c
> -static DWORD ReadChunk(CHAR *chunk, HANDLE hFile)
Why remove this function?

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/skel/win/2-crc/crc.c
> +     */
I don't think this is a better approach. The current skeleton and TODOs look clearer to me. Yes, they are more handholdy, but this exercise is more difficult than the others, so I think the more granular TODOs are justified.

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/skel/win/3-ls/ls.c
> + * @bRecursive  - if "ls -r" was issued
Should be `-R` so it's consistent with the POSIX `ls`.

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/skel/win/3-ls/ls.c
> +        /* save path */
```suggestion
        /* Save path */

```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/lin/3-mcat/mcat.c
> +
```suggestion
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/lin/3-mcat/mcat.c
> +
```suggestion

```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/1-cat/cat.c
> +    /* read file pointed by argv[1] and send it to standadard output */
```suggestion
    /* Read file pointed by argv[1] and send it to standadard output */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/1-cat/cat.c
> +    /* open file with name pointed by argv[1] */
```suggestion
    /* Open file with name pointed by argv[1] */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/1-cat/cat.c
> +        /* how much we've actually written */
```suggestion
        /* How much we've actually written */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/1-cat/cat.c
> +/* do not use UNICODE */
```suggestion
/* Do not use UNICODE */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/lin/5-singular/singular.c
> +     * deschiderea unui fisier cu flag-urile O_EXCL si O_CREAT
Translate this to English.

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/lin/4-trouble/trouble.c
> +    /* opening files */
```suggestion
    /* Open files */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/2-crc/crc.c
> +/* do not use UNICODE */
```suggestion
/* Do not use UNICODE */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/lin/5-singular/singular.c
> +    /* TODO - open file */
```suggestion
    /* TODO - Open file */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/lin/5-singular/singular.c
> +    /* TODO - lock the file using flock
```suggestion
    /* TODO - Lock the file using flock
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/lin/5-singular/singular.c
> +    /* TODO - unlock file, close file and delete it */
```suggestion
    /* TODO - Unlock file, close file and delete it */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/2-crc/crc.c
> +
```suggestion
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/2-crc/crc.c
> +    /* read from file  */
```suggestion
    /* Read from file  */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/2-crc/crc.c
> +        /* calculate crc for buf */
```suggestion
        /* Calculate crc for buf */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/3-ls/ls.c
> +/* do not use UNICODE */
```suggestion
/* Do not use UNICODE */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/3-ls/ls.c
> +/* enough to fit something like "1-ls.vcproj.CHOOCH.Administrator.user" */
```suggestion
/* Enough to fit something like "1-ls.vcproj.CHOOCH.Administrator.user" */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/3-ls/ls.c
> + * @bAll		- if "ls -a" was issued
```suggestion
 * List files from directory reprezented by path
 * @path	- path to dir we want to list
 * @bRecursive	- if "ls -R" was issued
 * @bAll	- if "ls -a" was issued
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/3-ls/ls.c
> +     -r - recursive
```suggestion
     -R - recursive
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/skel/win/3-ls/ls.c
> +     -r - recursive
```suggestion
     -R - recursive
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/4-trouble/trouble.c
> +/* do not use UNICODE */
```suggestion
/* Do not use UNICODE */
```

2022-02-21 21:18 UTC, teodutu commented on labs/lab02/sol/win/utils/utils.h
> +/* useful macro for handling error codes */
```suggestion
/* Useful macro for handling error codes */
```

2022-02-23 09:09 UTC, lucigrigo commented on labs/lab02/skel/win/2-crc/crc.c
> -}
this file from skel folder from so-internal did not contain the function, but the sol file did
when I copied the files I forgot to add it back

2022-02-23 09:10 UTC, lucigrigo commented on labs/lab02/skel/win/2-crc/crc.c
> -static DWORD ReadChunk(CHAR *chunk, HANDLE hFile)
same as above

2022-02-23 10:09 UTC, lucigrigo commented
Apparently I trusted my code formatting script too much (or too blindly :D).
I checked and fixed each file manually, hope I did not forget anything.

2022-02-23 10:44 UTC, teodutu requested changes
It's almost alright. There are a few more things you need to fix:
- Remove all `.DS_Store` files.
- Add the `tests_out` directory and the files inside it to `la02/skel/win/2-crc/tests`.
- Use tabs (`\t`), not spaces to align the `\`s within the `DIE` macros in all `utils.h` files.
- Capitalize the comments in `lab02/skel/lin/nasty/nasty.c`.

2022-02-23 10:44 UTC, teodutu commented on labs/lab02/skel/win/2-crc/crc.c
> +}
Add a newline at the end of the file.

2022-02-23 13:40 UTC, andreia-oca requested changes
Looks good to me. General suggestions are:
 - One variable declaration per line.
 - Delete the extra newline between the first comments and `include` from each source file.
 - The code should be indented using tabs, not spaces. (I suspect that the whole code is indented with spaces right now).
 
Use [checkpatch.pl](https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl) to check the indentation and potential trailing white spaces.

2022-02-23 13:40 UTC, andreia-oca commented on labs/lab02/skel/win/3-ls/ls.c
> +				/* TODO 3 - Recursive */
Why did you delete this hint? I think it makes sense to keep it.

2022-02-23 13:40 UTC, andreia-oca commented on labs/lab02/skel/win/3-ls/ls.c
> +	} while (/* TODO 1 - Interate if there are still files in list */ 0);
Typo `interate` -> `Iterate`

2022-02-23 13:40 UTC, andreia-oca commented on labs/lab02/sol/lin/3-mcat/mcat.c
> +	int fd, fd2, rc, bytesRead;
```suggestion
	int fd; 
	int fd2;
	int rc;
	int bytesRead;
```

2022-02-23 13:40 UTC, andreia-oca commented on labs/lab02/sol/lin/4-trouble/trouble.c
> +	int fd, rc;
```suggestion
	int fd;
	int rc;
```

2022-02-23 13:40 UTC, andreia-oca commented on labs/lab02/sol/win/1-cat/cat.c
> +	DWORD bytesRead, bytesWritten, totalWritten;
```suggestion
	DWORD bytesRead;
	DWORD bytesWritten;
	DWORD totalWritten;
```

2022-02-23 13:40 UTC, andreia-oca commented on labs/lab02/sol/win/2-crc/crc.c
> +	DWORD dwBytesWritten, dwBytesToWrite = sizeof(crc);
```suggestion
	DWORD dwBytesWritten;
	DWORD dwBytesToWrite = sizeof(crc);
```

2022-02-23 13:40 UTC, andreia-oca commented on labs/lab02/sol/win/3-ls/ls.c
> +	TCHAR extendedPath[MAXPATH], newPath[MAXPATH];
```suggestion
	TCHAR extendedPath[MAXPATH];
	TCHAR newPath[MAXPATH];

```

2022-02-26 14:00 UTC, lucigrigo commented
I believe that the newline between introduction comments and `/* Do not use UNICODE */` is fine. Where UNICODE comment is missing, that newline does not exist.

Double-checked all source files for space indent, but all of them were previously indented using tabs.

2022-02-26 16:47 UTC, teodutu requested changes
Just place the brackets on the same line as the `do` and `if` keywords and it's fine.

2022-02-26 16:47 UTC, teodutu commented on labs/lab02/skel/win/2-crc/tests/test_out/test1.out
> -����
Add this back. Do the same for the other tests (`test2.out`, `test3.out`) and copy them to the `sol` directory as well.

2022-02-26 16:47 UTC, teodutu commented on labs/lab02/skel/lin/utils/utils.h
> +		{								\
```suggestion
#define DIE(assertion, call_description)					\
	do {									\
		if (assertion) {						\
```

2022-02-26 16:47 UTC, teodutu commented on labs/lab02/skel/win/utils/utils.h
> +		{								\
```suggestion
#define DIE(assertion, call_description)					\
	do {									\
		if (assertion) {						\
```

2022-02-26 16:47 UTC, teodutu commented on labs/lab02/sol/win/utils/utils.h
> +		{								\
```suggestion
#define DIE(assertion, call_description)					\
	do {									\
		if (assertion) {						\
```

2022-02-27 12:22 UTC, teodutu approved these changes
Looks good!

2022-03-02 19:28 UTC, andreia-oca approved these changes
Looks good to me

2022-03-04 08:05 UTC, merged