Add solution for lab06
systems-cs-pub-ro/so pull request #27
Opened 2022-02-21 11:16 UTC by lucigrigo

2022-02-21 21:40 UTC, teodutu requested changes
I left some required changes as inline suggestions. The rest of the suggestions apply globally:

- Remove the `.DS_Store` and `labs/.DS_Store` files
- Revert the indentation from 4 spaces to tabs.
- Use the following style for multiline comments:
```
/**
 *
 */
```
- Use the Linux Kernel coding style for multiline `if`s, `for`s etc:
```c
if (cond) {
	/* stuff */
}
```
- In general, run `checkpatch.pl` and fix the coding style. Ignore the lack of an SPDX license and the CRLF line endings in Windows files.
- Start each comment with the capital letter, including the text after `/* TODO - ... */`.
- Use C90 comments (`/* ... */`), not C99 comments (`// ...`).
- Remove `labs/lab06/sol/.gitignore`. It's empty.
- Remove the empty line after the block comments at the beginning of `sol` files.

2022-02-21 21:40 UTC, teodutu commented on labs/lab06/skel/lin/3-efence/bug.c
> +    int *w = calloc(10, sizeof(int));
```suggestion
    int *v = calloc(10, sizeof(*v));
    int *w = calloc(10, sizeof(*w));
```

2022-02-21 21:40 UTC, teodutu commented on labs/lab06/skel/lin/7-paging/paging.c
> +    /*  perform real-time data changes */
```suggestion
    /* Perform real-time data changes */
```

2022-02-21 21:40 UTC, teodutu commented on labs/lab06/skel/win/4-prot/libvm.c
> -	/* TODO 2 - increase protection for that page */
Keep TODO numbers. They're useful for the students.

2022-02-21 21:42 UTC, teodutu commented on labs/lab06/skel/win/2-dyn/dyn.c
> +    0xC3                    /* ret              (3) */
Use 8-spaces wide tabs when indenting these.

2022-02-23 10:57 UTC, teodutu requested changes
The code looks about right. You still need to:
- Align the `\`s within `DIE` macros using tabs instead of spaces in all `utils.h` files.
- Remove `lab06/sol/.DS_Store`.

2022-02-23 10:57 UTC, teodutu commented on labs/lab06/skel/lin/4-cp/mycp.c
> +	/* TODO - truncate the output file to the input file size */
```suggestion
	/* TODO - Truncate the output file to the input file size */
```

2022-02-23 10:57 UTC, teodutu commented on labs/lab06/skel/lin/4-cp/mycp.c
> +	/* TODO - Mmap the input and output file */
```suggestion
	/* TODO - mmap the input and output file */
```

2022-02-23 10:57 UTC, teodutu commented on labs/lab06/skel/win/2-dyn/dyn.c
> +	0xC3                    /* ret              (3) */
Indent the comments using tabs, not spaces.

2022-02-23 10:57 UTC, teodutu commented on labs/lab06/sol/win/2-dyn/dyn.c
> +	0xC3                    /* ret              (3) */
Align the comments using tabs, not spaces.

2022-02-23 13:49 UTC, andreia-oca requested changes
Looks good to me. I added a few suggestions, mainly one-variable declaration per line.

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/skel/lin/5-prot/prot.c
> +	 * Comment this line when solving TODO 2
```suggestion
	 * Comment the line below when solving TODO 2
```

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/sol/lin/4-cp/mycp.c
> +	int fdin, fdout, rc;
```suggestion
	int fdin;
	int fdout;
	int rc;
```

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/sol/lin/4-cp/mycp.c
> +	char *src, *dst;
```suggestion
	char *src;
	char *dst;
```

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/sol/lin/7-paging/paging.c
> +	unsigned long page_offset, pagesize;
```suggestion
	unsigned long page_offset;
	unsigned long pagesize;
```

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/sol/lin/7-paging/paging.c
> +	unsigned long page_offset, pagesize;
```suggestion
	unsigned long page_offset;
	unsigned long pagesize;
```

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/sol/win/1-intro/intro.c
> +	DWORD rc, dwPageSize;
```suggestion
	DWORD rc;
	DWORD dwPageSize;
```

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/sol/win/4-prot/libvm.c
> +	DWORD old, rc;
```suggestion
	DWORD old;
	DWORD rc;
```

2022-02-23 13:49 UTC, andreia-oca commented on labs/lab06/sol/win/5-my_efence/my_efence.c
> +	/* int *v = malloc(10 * sizeof(int)); */
Delete this comment.

2022-02-26 17:09 UTC, teodutu requested changes
The number of tabs is a bit off at times. Other than that, it's looking good.

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/win/2-dyn/dyn.c
> +	0xC3					/* ret				(3) */
```suggestion
	0x8B, 0x44, 0x24, 0x04,	/* mov eax, [esp+4]	(1) */
	0x40,			/* inc eax		(2) */
	0xC3			/* ret			(3) */
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/sol/win/2-dyn/dyn.c
> +	0xC3					/* ret				(3) */
```suggestion
	0x8B, 0x44, 0x24, 0x04,	/* mov eax, [esp+4]	(1) */
	0x40,			/* inc eax		(2) */
	0xC3			/* ret			(3) */

```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/win/utils/utils.h
> +			perror(call_description);			\
Use `PrintLastError`. It's more specific on Windows.

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/sol/win/utils/utils.h
> +			perror(call_description);			\
Use `PrintLastError`. It's more specific on Windows.

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/win/2-dyn/dyn.c
> +										 MEM_COMMIT, PAGE_EXECUTE_READWRITE);
```suggestion
	dyncode = (int (*)(int))VirtualAlloc(NULL, pageSize,
			MEM_COMMIT, PAGE_EXECUTE_READWRITE);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/win/5-my_efence/my_efence.c
> +		__except (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ? EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH) {
Break this into multiple lines so they don't exceed 80 characters.

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/lin/1-intro/intro.c
> +			 PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
```suggestion
			PROT_READ | PROT_WRITE, MAP_PRIVATE, fd, 0);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/lin/1-intro/intro.c
> +			 MAP_ANONYMOUS | MAP_SHARED, -1, 0);
```suggestion
			MAP_ANONYMOUS | MAP_SHARED, -1, 0);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/lin/1-intro/intro.c
> +			 MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
```suggestion
			MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/lin/2-compare/mmap.c
> +			   MAP_SHARED, fd, 0);
```suggestion
			MAP_SHARED, fd, 0);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/lin/6-faults/fork-faults.c
> +			 MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
```suggestion
			MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/lin/8-hack/hack.c
> +	{
```suggestion
	if (mprotect(addr_aligned, pagesize,
		PROT_READ | PROT_WRITE | PROT_EXEC)) {
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/lin/8-hack/hack.c
> +		   ((int)*f != 0xb8 && (char)*((char *)f + 1) != 0x0c))
```suggestion
		((int)*f != 0xb8 && (char)*((char *)f + 1) != 0x0c))
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/skel/win/1-intro/intro.c
> +		PAGE_READWRITE); /* Protection */
```suggestion
		NULL,			/* System selects address */
		dwPageSize,		/* Size of allocation */
		MEM_COMMIT,		/* Allocate reserved pages */
		PAGE_READWRITE);	/* Protection */
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/sol/win/1-intro/intro.c
> +		PAGE_READWRITE); /* Protection */
```suggestion
		NULL,			/* System selects address */
		dwPageSize,		/* Size of allocation */
		MEM_COMMIT,		/* Allocate reserved pages */
		PAGE_READWRITE);	/* Protection */
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/sol/win/2-dyn/dyn.c
> +										 MEM_COMMIT, PAGE_EXECUTE_READWRITE);
```suggestion
	dyncode = (int (*)(int))VirtualAlloc(NULL, pageSize,
			MEM_COMMIT, PAGE_EXECUTE_READWRITE);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/sol/win/5-my_efence/my_efence.c
> +						PAGE_NOACCESS, &oldProt);
```suggestion
	rc = VirtualProtect(lpMem + dwNoPages * dwPageSize, dwPageSize,
		PAGE_NOACCESS, &oldProt);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/sol/win/5-my_efence/my_efence.c
> +						 MEM_COMMIT, PAGE_READWRITE);
```suggestion
	lpMem = VirtualAlloc(NULL, dwPageSize * (dwNoPages + 1),
		MEM_COMMIT, PAGE_READWRITE);
```

2022-02-26 17:09 UTC, teodutu commented on labs/lab06/sol/win/5-my_efence/my_efence.c
> +		__except (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ? EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH) {
Break this into multiple lines so that they don't exceed 80 characters.

2022-02-27 12:21 UTC, teodutu approved these changes
👍

2022-03-02 19:37 UTC, andreia-oca approved these changes
Looks good to me.

2022-03-04 08:05 UTC, merged