Add solution for lab10
systems-cs-pub-ro/so pull request #28
Opened 2022-02-21 11:23 UTC by lucigrigo

2022-02-21 22:10 UTC, teodutu requested changes
I left some required changes as inline suggestions. The rest of the suggestions apply globally:

- Remove the `.DS_Store` and `labs/.DS_Store` files
- Revert the indentation from 4 spaces to tabs.
- Use the following style for multiline comments:
```
/**
 *
 */
```
- Use the Linux Kernel coding style for multiline `if`s, `for`s etc:
```c
if (cond) {
	/* stuff */
}
```
- In general, run `checkpatch.pl` and fix the coding style. Ignore the lack of an SPDX license and the CRLF line endings in Windows files.
- Start each comment with the capital letter, including the text after `/* TODO - ... */`.
- Remove the empty lines after the block comments at the beginning of `sol` files.
- Remove the empty lines after the block comments that precede functions.
- Align the values of `#define`s using tabs:
```c
#define VALUE	1
#define STR	"something"
```
- Align the `\`s at the end of multiline `#define`s using tabs, not spaces.
- Align the comments at the end of successive lines using tabs, not spaces:
```c
foo(param_name1		/* explanation for param 1 */
	param_name2)	/* explanation for param 2 */
```
- Translate the comment at the beginning of `lab10/{skel,sol}/sock_utils.debug.h` to English.
- Move the content of `lab10/sol/lab-10/` to `lab10/sol/`.

2022-02-21 22:10 UTC, teodutu commented on labs/lab10/skel/lab-10/3-aio/aio.c
> -/* redefine BUFSIZ from 512 bytes to 4096 bytes. */
Keep this. It's important because, on Windows, libc defines BUFSIZ as 512 and not 8192 as it does on Linux.

2022-02-21 22:10 UTC, teodutu commented on labs/lab10/skel/lab-10/sock_utils/debug.h
> +#ifdef __GNUC__ // Linux
```suggestion
#ifdef __GNUC__ /* Linux */
```

2022-02-21 22:10 UTC, teodutu commented on labs/lab10/skel/lab-10/sock_utils/debug.h
> +#else // Windows
```suggestion
#else /* Windows */
```

2022-02-21 22:10 UTC, teodutu commented on labs/lab10/skel/lab-10/sock_utils/debug.h
> +{
```suggestion
enum LogType {
```

2022-02-21 22:10 UTC, teodutu commented on labs/lab10/skel/lab-10/1-test_overlapp/test_overlapp.c
> +                       NULL);                /* no template */
Align the comments using tabs, not spaces.

2022-02-21 22:10 UTC, teodutu commented on labs/lab10/sol/lab-10/sock_utils/debug.h
> +#ifdef __GNUC__  // Linux
```suggestion
#ifdef __GNUC__  /* Linux */
```

2022-02-21 22:10 UTC, teodutu commented on labs/lab10/sol/lab-10/sock_utils/debug.h
> +#else  // Windows
```suggestion
#else  /* Windows */
```

2022-02-23 13:53 UTC, andreia-oca requested changes
Looks good to me. A few inline suggestions.

2022-02-23 13:53 UTC, andreia-oca commented on labs/lab10/sol/1-test_overlapp/test_overlapp.c
> +	DWORD dwRet, dwErr, dwBytesRead;
```suggestion
	DWORD dwRet;
	DWORD dwErr;
	DWORD dwBytesRead;
```

2022-02-23 13:53 UTC, andreia-oca commented on labs/lab10/sol/2-transmit/server.c
> +	DWORD bytesWritten, dwRet;
```suggestion
	DWORD bytesWritten;
	DWROD dwRet;
```

2022-02-23 13:53 UTC, andreia-oca commented on labs/lab10/sol/3-aio/aio.c
> +	DWORD bytes_written, dwRet;
```suggestion
	DWORD bytes_written;
	DWORD dwRet;
```

2022-02-23 15:57 UTC, teodutu requested changes
There are still some things to fix, particularly regarding the alignment of `\`s and comments.

- Remove the `.DS_Store` files.
- Use the Linux Kernel style for the macros in `lab10/{skel,sol}/sock_utils/debug.h`:
```c
do {
	/* stuff */
} while (0)
```
- Use 8-space tabs when aligning `\`s in `lab10/{skel,sol}/sock_utils/debug.h` and `lab10/{skel,sol}/sock_utils/utils.h`.

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/.gitignore
> -*.txt
This `.gitignore` was actually useful. Bring it back.

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/1-test_overlapp/test_overlapp.c
> +					   NULL);                /* No template */
Use tabs when aligning the comments.

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/3-aio/aio.c
> +	fds = (HANDLE *)malloc(n_files * sizeof(HANDLE));
```suggestion
	fds = malloc(n_files * sizeof(*fds));
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/3-aio/aio.c
> +							HANDLE hEvent)
```suggestion
static void init_overlapped(OVERLAPPED *lpo, DWORD offset, HANDLE hEvent)
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/generator/generator.c
> +	buffer = calloc(noBytes + 1, sizeof(char));
```suggestion
	sscanf_s(argv[1], "%i", &noBytes, sizeof(noBytes));
	buffer = calloc(noBytes + 1, sizeof(*buffer ));
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +#ifdef __GNUC__ // Linux
```suggestion
#ifdef __GNUC__ /* Linux */
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/sock_utils/sock_util.c
> +
```suggestion
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/.gitignore
> -tema5
This `.gitignore` file is useful. Bring it back.

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/1-test_overlapp/test_overlapp.c
> +	char *buffer = malloc(BUF_SIZE * sizeof(char));
```suggestion
	char *buffer = malloc(BUF_SIZE * sizeof(*buffer));
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/1-test_overlapp/test_overlapp.c
> +					   NULL);                /* No template */
Use tabs to align the comments, not spaces.

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/2-transmit/transmit_client.c
> +	{
```suggestion
	if (argc != 2) {
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/3-aio/aio.c
> +	fds = (HANDLE *)malloc(n_files * sizeof(HANDLE));
```suggestion
	fds = malloc(n_files * sizeof(*fds));
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/4-iocp/aio.c
> +
```suggestion
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/3-aio/aio.c
> +
```suggestion
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/2-transmit/transmit_client.c
> +
```suggestion
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/generator/generator.c
> +
```suggestion
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/4-iocp/iocp.c
> +
```suggestion
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> + * Filename: log.h
```suggestion
 * Filename: debug.h
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/sock_utils/sock_util.c
> +/* do not use UNICODE */
```suggestion
/* Do not use UNICODE */
```

2022-02-23 15:57 UTC, teodutu commented on labs/lab10/sol/sock_utils/sock_util.c
> +
```suggestion
```

2022-02-26 17:42 UTC, teodutu requested changes

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/.gitignore
> +tema5
This is not needed.

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/.gitignore
> +tema5
Not needed.

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/1-test_overlapp/test_overlapp.c
> +						NULL);					/* No template */
```suggestion
	hFile = CreateFile(argv[1],
		GENERIC_READ,		/* Access mode */
		FILE_SHARE_READ,	/* Sharing option */
		NULL,			/* Security attributes */
		OPEN_EXISTING,		/* Open only if it exists */
		FILE_FLAG_OVERLAPPED,	/* File attributes */
		NULL);			/* No template */
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/2-transmit/server.c
> +									 SERVER_BACKLOG);
```suggestion
	hListen = tcp_listen_connections(SERVER_LISTEN_PORT,
		SERVER_BACKLOG);
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/1-test_overlapp/test_overlapp.c
> +											&dwBytesRead, TRUE);
```suggestion
				dwRet = GetOverlappedResult(ov.hEvent, &ov,
					&dwBytesRead, TRUE);
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/generator/generator.c
> +	{
```suggestion
	if (argc != 3) {
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/generator/generator.c
> +					   NULL);
```suggestion
				GENERIC_WRITE,
				0,
				NULL,
				CREATE_ALWAYS,
				FILE_ATTRIBUTE_NORMAL,
				NULL);
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +	error_buffer = strerror_r(errno, error_buffer, sizeof(error_buffer));
```suggestion
#define LOG_GET_ERROR_MESSAGE							\
	char *error_buffer;							\
	char error_buffer2[512];						\
	error_buffer = error_buffer2;						\
	error_buffer = strerror_r(errno, error_buffer, sizeof(error_buffer));
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/1-test_overlapp/test_overlapp.c
> +						NULL);					/* No template */
```suggestion
		GENERIC_READ,		/* Access mode */
		FILE_SHARE_READ,	/* Sharing option */
		NULL,			/* Security attributes */
		OPEN_EXISTING,		/* Open only if it exists */
		FILE_FLAG_OVERLAPPED,	/* File attributes */
		NULL);			/* No template */
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/2-transmit/server.c
> +									 SERVER_BACKLOG);
```suggestion
		SERVER_BACKLOG);
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/4-iocp/aio.c
> +#define IO_OP_TYPE IO_ASYNC
```suggestion
#define IO_SYNC		1
#define IO_ASYNC	2
#define IO_OP_TYPE	IO_ASYNC
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/4-iocp/aio.c
> +#define BUFSIZ 4096
```suggestion
#define BUFSIZ		4096
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/4-iocp/aio.c
> +	fds = (HANDLE *)malloc(n_files * sizeof(HANDLE));
```suggestion
	fds = malloc(n_files * sizeof(*fds));
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/generator/generator.c
> +					   NULL);
```suggestion
	hFile = CreateFile(argv[2],
		GENERIC_WRITE,
		0,
		NULL,
		CREATE_ALWAYS,
		FILE_ATTRIBUTE_NORMAL,
		NULL);
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +#ifdef __GNUC__ // Linux
```suggestion
#ifdef __GNUC__  /* Linux */
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +	error_buffer = strerror_r(errno, error_buffer, sizeof(error_buffer));
```suggestion
#define LOG_GET_ERROR_MESSAGE							\
	char *error_buffer;							\
	char error_buffer2[512];						\
	error_buffer = error_buffer2;						\
	error_buffer = strerror_r(errno, error_buffer, sizeof(error_buffer));
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +#else // Windows
```suggestion
#else  /* Windows */
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +		sizeof(error_buffer),										\
```suggestion
#define LOG_GET_ERROR_MESSAGE										char error_buffer[512];							\
	FormatMessage(								\
		FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_MAX_WIDTH_MASK,	\
		NULL,								\
		GetLastError(),							\
		0,								\
		error_buffer,							\
		sizeof(error_buffer),						\
		NULL);
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +{
```suggestion
enum LogType {
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +		}																		\
```suggestion
#define LOG(type, ...)							\
	do {								\
		if (type <= LOG_LEVEL) {				\
			if (type <= DEBUG)				\
				fprintf(stderr, " %c", " FWID"[type]);	\
			else						\
				fprintf(stderr, "%02d", type - DEBUG);	\
									\
			fprintf(stderr, " %s (%s) %d: ", __FILE__,	\
				__FUNCTION__, __LINE__);		\
			fprintf(stderr, __VA_ARGS__);			\
			fprintf(stderr, "\n");				\
			fflush(stderr);					\
									\
			/* Abort() is C89 compliant. */			\
			if (type == FATAL)				\
				abort();				\
		}							\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +		LOG(FATAL, "Last error: %s.", error_buffer);	\
```suggestion
#define LOG_ERROR(...)						\
	do {							\
		LOG_GET_ERROR_MESSAGE				\
		LOG(NONE, __VA_ARGS__);				\
		LOG(FATAL, "Last error: %s.", error_buffer);	\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +		}													\
```suggestion
#define ASSERT(condition)						\
	do {								\
		if (!(condition)) {					\
			LOG_GET_ERROR_MESSAGE				\
			LOG(NONE, "ASSERT failed: %s.", #condition);	\
			LOG(FATAL, "Last error: %s.", error_buffer);	\
		}							\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +		}																		\
```suggestion
#define CHECK(left, operation, right)					\
	do {								\
		if (!((left)operation(right))) {			\
			LOG_GET_ERROR_MESSAGE				\
			LOG(NONE, "CHECK failed: %s %s %s.", #left,	\
				#operation, #right);			\
			LOG(FATAL, "Last error: %s.", error_buffer);	\
		}							\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/skel/utils/utils.h
> +			perror(call_description);			\
```suggestion
			PrintLastError(call_description);		\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/1-test_overlapp/test_overlapp.c
> +	{
```suggestion
	if (argc != 2) {
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +#ifdef __GNUC__ // Linux
```suggestion
#ifdef __GNUC__  /* Linux */
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +#else // Windows
```suggestion
#else  /* Windows */
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +		sizeof(error_buffer),										\
```suggestion
#define LOG_GET_ERROR_MESSAGE							\
	char error_buffer[512];							\
	FormatMessage(								\
		FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_MAX_WIDTH_MASK,	\
		NULL,								\
		GetLastError(),							\
		0,								\
		error_buffer,							\
		sizeof(error_buffer),						\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +{
```suggestion
enum LogType {
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +		}																		\
```suggestion
#define LOG(type, ...)							\
	do {								\
		if (type <= LOG_LEVEL) {				\
			if (type <= DEBUG)				\
				fprintf(stderr, " %c", " FWID"[type]);	\
			else						\
				fprintf(stderr, "%02d", type - DEBUG);	\
									\
			fprintf(stderr, " %s (%s) %d: ", __FILE__,	\
				__FUNCTION__, __LINE__);		\
			fprintf(stderr, __VA_ARGS__);			\
			fprintf(stderr, "\n");				\
			fflush(stderr);					\
									\
			/* Abort() is C89 compliant. */			\
			if (type == FATAL)				\
				abort();				\
		}							\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +		LOG(FATAL, "Last error: %s.", error_buffer);	\
```suggestion
#define LOG_ERROR(...)						\
	do {							\
		LOG_GET_ERROR_MESSAGE				\
		LOG(NONE, __VA_ARGS__);				\
		LOG(FATAL, "Last error: %s.", error_buffer);	\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +		}													\
```suggestion
#define ASSERT(condition)						\
	do {								\
		if (!(condition)) {					\
			LOG_GET_ERROR_MESSAGE				\
			LOG(NONE, "ASSERT failed: %s.", #condition);	\
			LOG(FATAL, "Last error: %s.", error_buffer);	\
		}							\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/sock_utils/debug.h
> +		}																		\
```suggestion
#define CHECK(left, operation, right)					\
	do {								\
		if (!((left)operation(right))) {			\
			LOG_GET_ERROR_MESSAGE				\
			LOG(NONE, "CHECK failed: %s %s %s.", #left,	\
				#operation, #right);			\
			LOG(FATAL, "Last error: %s.", error_buffer);	\
		}							\
```

2022-02-26 17:42 UTC, teodutu commented on labs/lab10/sol/utils/utils.h
> +			perror(call_description);			\
```suggestion
			PrintLastError(call_description);		\
```

2022-02-26 19:53 UTC, teodutu requested changes
Sorry I missed a few coding style errors during the last review. After fixing these new suggestions, all should be fine on my part

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/1-test_overlapp/test_overlapp.c
> +											&dwBytesRead, TRUE);
```suggestion
				dwRet = GetOverlappedResult(ov.hEvent, &ov,
					&dwBytesRead, TRUE);
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/4-iocp/aio.c
> +							HANDLE hEvent)
```suggestion
	HANDLE hEvent)
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/generator/generator.c
> +	{
```suggestion
	if (argc != 3) {
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/sock_utils/sock_util.c
> +				sizeof(server_addr)) < 0) {
```suggestion
	if (connect(s, (struct sockaddr *)&server_addr,
		sizeof(server_addr)) < 0) {
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/sock_utils/sock_util.c
> +		   sizeof(server_addr.sin_addr.s_addr));
```suggestion
	memcpy(&server_addr.sin_addr.s_addr, hent->h_addr,
		sizeof(server_addr.sin_addr.s_addr));
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/sock_utils/sock_util.c
> +				   (const char *)&sock_opt, sizeof(int)) < 0) {
```suggestion
	if (setsockopt(listenfd, SOL_SOCKET, SO_REUSEADDR,
		(const char *)&sock_opt, sizeof(int)) < 0) {
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/sock_utils/sock_util.c
> +		   ntohs(address->sin_port));
```suggestion
	printf("Connected with %s:%d\n", inet_ntoa(address->sin_addr),
		ntohs(address->sin_port));
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/sol/1-test_overlapp/test_overlapp.c
> +				break;
```suggestion
		case ERROR_HANDLE_EOF:
			/* Reached end of file */
			printf("End of File Reached\n");
			break;

		case ERROR_IO_PENDING:
			/* Async io not ready */
			printf("Async IO did not finished immediately\n");

			/* Do some other work  in the meantime*/
			printf("Waiting for IO to finish\n");
			while (doWork--)
				;

			/* Wait for it to finish */
			dwRet = GetOverlappedResult(ov.hEvent, &ov,
				&dwBytesRead, TRUE);
			printf("nRead = %d\n", dwBytesRead);
			break;

		default:
			/* ReadFile failed */
			PrintLastError("ReadFile");
			break;
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/sol/generator/generator.c
> +				NULL);
```suggestion
		GENERIC_WRITE,
		0,
		NULL,
		CREATE_ALWAYS,
		FILE_ATTRIBUTE_NORMAL,
		NULL);
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/.gitignore
> -*.txt
My bad, these lines should be in the `.gitignore`. I only meant to say the last line `tema5` should be removed.

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/sol/.gitignore
> -*.txt
The same as `lab10/skel/.gitignore`

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/skel/sock_utils/debug.h
> +	FormatMessage(								\
```suggestion
#define LOG_GET_ERROR_MESSAGE
	char error_buffer[512];							\
	FormatMessage(								\
```

2022-02-26 19:53 UTC, teodutu commented on labs/lab10/sol/2-transmit/server.c
> +	{
```suggestion
	while (1) {
```

2022-02-27 10:45 UTC, teodutu approved these changes
Looks good.

2022-03-02 19:54 UTC, andreia-oca approved these changes
Looks ok to me.

2022-03-04 08:06 UTC, merged