Recap lab: Fix exercises and publish solution
systems-cs-pub-ro/so pull request #35
Opened 2022-03-14 15:49 UTC by teodutu

2022-03-15 13:01 UTC, sketch873 requested changes
It looks nice. There are only few suggestions regarding extra tabs/spaces

2022-03-15 13:01 UTC, sketch873 commented on labs/recap/skel/09-syscall/pid_test.c
> +/**
Please remove extra tabs/spaces

2022-03-15 13:01 UTC, sketch873 commented on labs/recap/skel/10-fork/fork.c
> +	if (fork() >  0)
Please remove extra tabs

2022-03-15 13:01 UTC, sketch873 commented on labs/recap/skel/11-fds/fd.c
> +{
Please remove extra tab

2022-03-15 13:01 UTC, sketch873 commented on labs/recap/skel/11-fds/fd.c
> +
Another tab here

2022-03-15 13:01 UTC, sketch873 commented on labs/recap/skel/12-file/file.c
> +#include <unistd.h>
Please remove extra tab

2022-03-15 13:01 UTC, sketch873 commented on labs/recap/skel/12-file/file.c
> +#include <unistd.h>
Actually there are two, the second one on line 20.

2022-03-19 09:52 UTC, lucigrigo submitted a review, later dismissed

2022-03-19 09:57 UTC, sketch873 approved these changes, later dismissed

2022-03-21 10:37 UTC, andreia-oca requested changes
Looks great to me.

There are some notes in `labs/recap/sol/` that are currently in Romanian:
 - `labs/recap/sol/README.md`
 - `labs/recap/sol/02-io/run_out`
 - `labs/recap/sol/02-io/README.md`

IMO, I think we should translate them in English.

2022-03-21 10:37 UTC, andreia-oca commented on labs/recap/skel/01-cow/cow.c
> +
Please remove this extra empty line.

2022-03-21 10:37 UTC, andreia-oca commented on labs/recap/sol/02-io/README.md
> +Dacă folosim un fişier care este deja în memorie (cum ar fi `/dev/zero`), se va vedea o diferenţă notabilă doar la trunchierea fişierului.
IMO This should be translated into English.

2022-03-21 10:37 UTC, andreia-oca commented on labs/recap/sol/02-io/run_out
> +0:04.19
Same as above, I think this note should be translated in English.

2022-03-21 10:37 UTC, andreia-oca commented on labs/recap/sol/README.md
> +Paginile mapate inițial read-only sunt remapate read-write în urma page faulturilor.
Same as above, I think this note should be translated in English.

2022-03-22 09:24 UTC, andreia-oca approved these changes
Thanks. Looks great to me.

2022-03-22 10:35 UTC, merged