infrastructure: Upgrade VM to Ubuntu 20.04, misc fixes and clean-up
systems-cs-pub-ro/so pull request #7
Opened 2021-02-28 20:01 UTC by CajuM

2021-02-28 20:07 UTC, CajuM commented
I should note that tests currently don't work for homeworks. I'm guessing it's due to diff output of timestamps. Sample:
```
Incorrect number of faults: got 3, expected  2
05) Test data and bss.......................................failed  [ 0/95]
_test/outputs/test5.out vs _test/refs/test5.ref:
--- _test/outputs/test5.out     2021-02-28 21:35:24.629923754 +0200
+++ _test/refs/test5.ref        2021-02-28 21:15:59.000000000 +0200
@@ -0,0 +1 @@
+SUCCESS
```

2021-03-01 13:00 UTC, edi33416 requested changes
LGTM

Please also get in touch with someone from the Homeworks team to double check.

Have you checked that the VM is working properly with the homeworks skeletons?

2021-03-01 13:00 UTC, edi33416 commented on infrastructure/vm/playbooks-common/helper-pkgs.yml
> +    # open-vm-tools is necesary for exporting to VMware
```suggestion
    # open-vm-tools are necessary for exporting to VMware
```

2021-03-01 14:06 UTC, CajuM commented
> LGTM
> 
> Please also get in touch with someone from the Homeworks team to double check.
> 
> Have you checked that the VM is working properly with the homeworks skeletons?

I verified all the homework checkers. They all compile, but some throw errors when ran on the solution. At least in one case the solution was poorly written.

2021-03-03 17:34 UTC, CajuM commented
* tema1: ok
* tema2: ok
* tema3: problem with solution
* tema4: ok
* team5: ok

2021-03-03 18:46 UTC, edi33416 commented on infrastructure/vm/vagrantfile-so/publish.sh
> +vagrant cloud publish edi33416/so-ubuntu-20.04 1.1.0 virtualbox so-ubuntu-20-04.box -d "Ubuntu 20.04 based on bento/ubuntu-20.04 and provisioned with Ansible" --version-description "Latest stable ver
```suggestion
vagrant cloud publish edi33416/so-ubuntu-20.04 1.3.0 virtualbox so-ubuntu-20-04.box -d "Ubuntu 20.04 based on bento/ubuntu-20.04 and provisioned with Ansible" --version-description "Latest stable version" --release --short-description "SO VM"
```

2021-03-03 18:47 UTC, edi33416 commented on infrastructure/vm/vagrantfile-so/publish.sh
> +vagrant cloud publish edi33416/so-ubuntu-20.04 1.1.0 virtualbox so-ubuntu-20-04.box -d "Ubuntu 20.04 based on bento/ubuntu-20.04 and provisioned with Ansible" --version-description "Latest stable ver
Bump the version to 1.3.0, as there is 1.2.0 is the current [release](https://app.vagrantup.com/edi33416/boxes/so-ubuntu-18.04/versions/1.2.0)

2021-03-03 19:31 UTC, edi33416 commented on infrastructure/vm/vagrantfile-so/publish.sh
> +vagrant cloud publish systems-cs-pub-ro/so 1.3.0 virtualbox so-ubuntu-20-04.box -d "Ubuntu 20.04 based on bento/ubuntu-20.04 and provisioned with Ansible" --version-description "Latest stable version
```suggestion
vagrant cloud publish systems-cs-pub-ro/so 2.0.0 virtualbox so-ubuntu-20-04.box -d "Ubuntu 20.04 based on bento/ubuntu-20.04 and provisioned with Ansible" --version-description "Latest stable version" --release --short-description "SO VM"
```

2021-03-03 19:41 UTC, edi33416 approved these changes
Nice job!

Please make sure to cleanup the image before publishing it, to keep the size small.

Have a look at [this StackOverflow](https://stackoverflow.com/a/35733376) answer.

You could use [this ](https://gist.github.com/adrienbrault/3775253) cleanup script; probably you'll need to replace `#!/bin/sh` with `#!/bin/bash`

2021-03-03 19:43 UTC, merged